version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - todo

  mysql_db:
    image: mysql:latest
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - todo

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - todo

networks:
  todo:
    driver: bridge
